### ISSUE TITLE
How did you get started in open source?

### ISSUE THREAD

**Issue by libuk** [zoepage/ama#10]
You mentioned in an earlier answer about learning more from open source than university. I still find open source a little scary, how did you first get involved?

**Comment by zoepage** [comment]
That is a great question @libuk. Thank you for that. :)

Open Source can be scary, especially from the outside. This is why it took me forever to get involved. I guess, I was pretty lucky in general. I got involved in the community through conference / meetup orga few years back and had the chance getting to know a lot of lovely humans, that were in OS already. That took away a lot of fear as the project's weren't  "faceless" anymore. 
Through that connection, I got a job offer to work in an OS project full-time. I had the chance to learn from great people about how its done as well as got motivated to keep going.

I know, the way I got involved is not very typical, but through the years, I've seem a few ways how to get involved. (I feel like this is also a part of your question?)

At first, it helps a lot to think about what you'd like to contribute, how much time would you like to invest and the reason why you'd like to contribute. Don't be shy about the "what". Not just the "shipping a huge feature" contributions are crucial. Actually the smaller ones from reviewing code, give feedback in discussions to just fixing a typo or writing a bug are super helpful. So start where ever you feel comfortable. If you'd like to contribute on a regular basis, set a time slot for yourself, e.g. once a week every Thursday and stick to it. If you prefer to contribute from time to time, great! Just pick small tasks in the beginning and have fun with it.

There are great projects like https://yourfirstpr.github.io/ that give some info for beginners as well as collect "starter issues". Starter issues help you to get on board of a project. The task is smaller most of the times and explained in detail as those are all about the experience of a first PR (as in pull request). 

When you look for a project, look around if you find something that matches your tone of communication and makes you feel comfortable or you'll learn something specific you'd like to etc. Here it's handy to be aware of your reasons, why you'd like to contribute to open source. Check if there is an activity in the issues, does the project value PRs? Or are they too focused on code or something else? 

There are so many open source projects out there that would love to hear from you. You just have to find one that fits you and your needs. :)

**Comment by libuk** [comment]
@zoepage Thank you for the considered answer. The questions around time and what I'd like to learn are especially helpful :)

**Comment by bgarcial** [comment]
@zoepage Great advices. Thanks.
