### ISSUE TITLE
what is your take on cats?

### ISSUE THREAD

**Issue by yoshuawuyts** [zoepage/ama#2]
Do you like them? Are you allergic? How many cats is too many?

**Comment by zoepage** [comment]
Puuuuurrrrrrrr!
I love that the internet got it's reason to live, thanks to cat gifs.

Personally I'm more a [dog](http://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-1.png) person ;)

**Comment by yoshuawuyts** [comment]
:smile_cat:

**Comment by TheLarkInn** [comment]
❤️🐕
