### ISSUE TITLE
How did you get involved into OTS?

### ISSUE THREAD

**Issue by yangwao** [zoepage/ama#5]
I've been at 32c3 in Hamburg as well and I never heard about OpenTechSchool, how did you get involved? I'd like spark something similiar in Bratislava, Slovakia as well :)

Cheers

**Comment by zoepage** [comment]
I used to live in Berlin and moved away to Dortmund. There was almost no community / meetups etc and it was kind of a shock after having it all in Berlin. This is why we created one chapter in Dortmund. Took quite some time to get people involved, but it grew. After 3 years, we even managed to organize a whole conference.

You are able to start an OTS chapter in your city. It is free and the concept is a blueprint. All you need is a space and some people, who help to organize it with you. Materials and infrastructure is provided.
http://www.opentechschool.org/handbooks/city-blueprint.html
