### ISSUE TITLE
What is "daughter driven development"?

### ISSUE THREAD

**Issue by jacobwardio** [zoepage/ama#9]
You've mentioned "daughter driven development" in a number of places. I was just wondering if this is an actual process/philosophy you have towards development or just something a little clever and funny?

**Comment by zoepage** [comment]
That is actually a really good question. Thank you for that :)

It's both... I'm a solo mom, so my day is pretty organised as well as I work in a very different way than others. E.g. I have specific time slots every day, so have to be very efficient in my work as well as plan "in the zone" blocks in advance. My work is mostly pretty good documented as my daughter might suddenly get sick and I am not around, so someone can take over at any point. 

Summed up, it's a very specific way of developing your applications. :)
